### ISSUE TITLE
testers2 fails to compile

### ISSUE THREAD

**Issue by tampler** [freechipsproject/twerk#2]
Hi @chick 

I tried to launch your test from the testers2 branch, but it won't compile.
Could you pls check it out and fix.

Thanks

**Comment by chick** [comment]
See comments on PR #1 
Problem is with published snapshot of testers2.
Should be re-published with latest changes by tomorrow afternoon

**Comment by tampler** [comment]
Thank you. Solved in a new master

**Comment by ducky64** [comment]
A new snapshot of testers2 has been published against current snapshots of chisel3/firrtl. I'm not sure if it did anything useful, since it appears the breaking changes in chisel3 haven't been pushed to a snapshot yet.

In general snapshots of testers2 will track snapshots of chisel3/firrtl and are not guaranteed to be compatible with master. If you're building chisel3/firrtl from source, you may also need to build testers2 from source.

**Comment by tampler** [comment]
Thanks, Richard. I'm working on a new simulator for Chisel with efficient [Chat](https://github.com/Neurodyne/chat) support. I'll deliver a talk on that soon...
